#!/usr/bin/env sh

cd vendor && rm -rf $(ls | grep -v bundle) && cd ..

BUNDLE=$(which bundle) || BUNDLE="NULL"
if [ "${BUNDLE}" = "NULL" ]; then
  gem install bundler
fi

rm -rf .bundle
#bundle install --path=vendor/bundle
RAILS_ENV=production bundle install --deployment --without test development

